const htmlQ=[
  
    {   
        id:"gsj",
        question:"which of the following is a way to configure the amount of space between words ?",
        opt:["word-margin",
        "letter-margin",
        "word-spacing",
        "word-padding"],
        ans:"opt3", 
    },
    {   
        id:"dkkjnjjssjsjshaziaiao",
        question:"which HTML5 element you use to organise content so that the page maximizes a search engine algorithm ?",
        opt:['&ltdiv id="CompanyNews"&gt',
        "&ltheader&gtCompany News&lt/header&gt",
        "&ltarticle&gtCompany News&lt/article&gt",
        "All of the above "],
        ans:"opt3",
    },
    {  
        id:"skjieahhiual",
        question:"Which one of the following is an attribute selector?",
        opt:[".required","#required","input[required]",":required"],
        ans:"opt3",
    },
    {  
        id:"skjiewww",
        question:"Which HTML attribute is used to define inline styles?",
        opt:["styles","font","class","style"],
        ans:"opt4",
    },
    {  
        id:"shadijikjwwjahuaw",
        question:"How do you display hyperlinks without an underline?",
        opt:["a{decoration:no-underline}",
        "a{text-decoration:no-underline}",
        "a{underline:none}",
        "a{text-decoration:none}"],
        ans:"opt4",
    },
    {  
        id:"skhsaospqwww",
        question:"How do you make each word in a text start with a capital letter?",
        opt:["transform:capitalize","You can't do that with css",
        "text-transform:capitalize","text-style:capitalize"],
        ans:"opt3",
    },
    {  
        id:"sspspsmssiwww",
        question:"How do you select all p elements inside a div element?",
        opt:["div p","div + p","div.p","div,p"],
        ans:"opt1",
    },
    {  
        id:"sspspsmssiwww",
        question:"What is the default value of the position property?",
        opt:["relative","static","fixed","absolute"],
        ans:"opt2",
    },
    {  
        id:"sspspsmssiwww",
        question:"What does HTML stand for?",
        opt:["Hyper Text Markup Language","Home Tool Markup Language ",
        "Hyperlinks Text Markup Language","Home Tool Markup Language"],
        ans:"opt1",
    },
    {  
        id:"sspspsmssiwww",
        question:"Choose the correct HTML element to define important text?",
        opt:["&ltb&gt","&ltstrong&gt","&ltimportant&gt","&lti&gt"],
        ans:"opt2",
    },
    {  
        id:"sspspsmssiwww",
        question:"What is the correct HTML for making a text input field?",
        opt:['&ltinput type="text"&gt',"&lttextfield&gt",'&lttextinput type="text"&gt','&ltinput type="textfield"&gt'],
        ans:"opt1",
    },
    {  
        id:"sspspsmssiwww",
        question:"Which HTML element defines the title of a document?",
        opt:["&lthead&gt","&lttitle&gt","&ltmeta&gt","&ltbody&gt"],
        ans:"opt2",
    },
    {  
        id:"sspspsmssiwww",
        question:"Which HTML attribute specifies an alternate text for an image, if the image cannot be displayed?",
        opt:["title","alt","longdesc","src"],
        ans:"opt2",
    },
    {  
        id:"sspspsmssiwww",
        question:"What is the correct HTML element for playing video files?",
        opt:["&ltvideo&gt","&ltmedia&gt","&ltmovie&gt","&ltvideos&gt"],
        ans:"opt1",
    },
    {  
        id:"sspspsmssiwww",
        question:'The HTML global attribute, "contenteditable" is used to:',
        opt:["Update the content from the server",
        "Specify whether the content of an element should be editable or not",
        "specify a context menu for an element. the menu appears when a user right-click on the element ",
        "return the position of the first found occurrence of content inside a string"],
        ans:"opt2",
    }
];